/* client-src/10-css.js — 广场与对话页 CSS */


    // ---------------------------------------------------------------------
    // CSS：广场主内容区观感（浅色、顶部栏、卡片网格；深色跟随 DSH 主题）。
    // ---------------------------------------------------------------------
    var CSS = [
      ".kwp-fixed{position:fixed;top:0;right:0;bottom:0;left:280px;z-index:2147483647!important;isolation:isolate;background:#fcfcfc;color:#18181a;font-family:'Geist Variable','Alimama ShuHeiTi',-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei','Segoe UI',sans-serif;-webkit-font-smoothing:antialiased;display:flex;flex-direction:column;min-width:0;min-height:0;overflow:hidden;pointer-events:auto}",
      ".kwp-emptyHint{color:#8b95a3;font-size:12px;padding:4px 12px}",
      ".kwp-topbar{display:flex;align-items:center;gap:12px;padding:14px 28px;background:transparent;flex:none}",
      ".kwp-title{font-size:15px;font-weight:600;line-height:20px}",
      ".kwp-content{padding:0 28px 22px;overflow:auto;flex:1;min-height:0}",
      ".kwp-grid{display:grid;grid-template-columns:1fr;gap:18px;align-content:start}",
      "@media (min-width:640px){.kwp-grid{grid-template-columns:repeat(2,1fr)}}",
      "@media (min-width:1024px){.kwp-grid{grid-template-columns:repeat(3,1fr)}}",
      "@media (min-width:1536px){.kwp-grid{grid-template-columns:repeat(4,1fr)}}",
      "@media (min-width:900px){.kwp-grid{gap:32px}}",
      ".kwp-card{appearance:none;font-family:inherit;text-align:left;cursor:pointer;color:#0f172a;background:#ffffff;border:1px solid #f6f6f6;border-radius:20px;padding:12px 10px;display:flex;flex-direction:column;position:relative;overflow:visible;transition:box-shadow .2s ease}",
      ".kwp-card:hover:not(:disabled){box-shadow:0 16px 30px 0 rgba(0,0,0,.10)}",
      ".kwp-card:active:not(:disabled){box-shadow:0 8px 16px 0 rgba(0,0,0,.08)}",
      ".kwp-card:disabled{cursor:default;opacity:.65}",
      ".kwp-cardBand{position:relative;display:flex;align-items:center;gap:10px;border-radius:18px;height:68px;background:#f6f6f6;padding:8px;margin-top:34px;box-sizing:border-box}",
      ".kwp-avatarBox{position:relative;width:80px;flex:none;align-self:stretch}",
      ".kwp-avatarInner{position:absolute;left:0;bottom:8px;width:80px;height:94px;border-radius:18px;display:flex;align-items:center;justify-content:center;font-size:30px;font-weight:700;color:#fff;overflow:hidden}",
      ".kwp-id{flex:1;min-width:0;display:flex;flex-direction:column;gap:2px}",
      ".kwp-name{font-size:12px;font-weight:700;color:#18181a;line-height:1.5;display:flex;align-items:baseline;gap:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-handle{font-weight:400;color:#9ca3af;font-size:11px}",
      ".kwp-role{font-size:10px;color:#757f9c;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-online{display:inline-flex;align-items:center;gap:2px;padding:2px 4px;font-size:8px;font-weight:600;color:#757f9c;border-radius:90px;background:#fff;width:fit-content;line-height:1.2}",
      ".kwp-online i{width:6px;height:6px;border-radius:50%;background:#22c55e;flex:none;display:inline-block}",
      ".kwp-chatBtn{width:28px;height:28px;border-radius:10px;background:#fff;color:#757f9c;display:flex;align-items:center;justify-content:center;flex:none;align-self:center;transition:color .15s}",
      ".kwp-card:hover .kwp-chatBtn{color:#18181a}",
      ".kwp-desc{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;margin-top:8px;height:36px;flex:none;font-size:12px;line-height:18px;color:#757f9c}",
      ".kwp-tags{display:flex;flex-wrap:wrap;gap:10px;margin:8px 0;align-items:center}",
      ".kwp-wtag{border-radius:20px;padding:0 8px;font-size:10px;line-height:13px;color:#757f9c;border:1px solid #e3e7f1;white-space:nowrap}",
      ".kwp-stats{margin-top:auto;display:grid;grid-template-columns:repeat(3,1fr);border-radius:14px;border:1px solid #e3e7f1;box-sizing:border-box}",
      ".kwp-statCell{display:flex;flex-direction:column;justify-content:center;gap:4px;padding:6px 20px;border-right:1px solid #eef1f5}",
      ".kwp-statCell:last-child{border-right:0}",
      ".kwp-statValue{font-size:18px;line-height:24px;font-weight:700;color:#18181a}",
      ".kwp-statLabel{font-size:10px;color:#464c5e;font-style:normal}",
      ".kwp-hint{font-size:12px;color:#8b95a3;margin-top:6px;text-align:center}",
      ".kwp-loading{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#5b6675;font-size:14px}",
      ".kwp-error{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#dc2626;font-size:14px}",
      ".kwp-back{display:flex;align-items:center;gap:2px;flex:none;border:0;background:transparent;color:#757f9c;font-size:13px;font-weight:500;padding:6px 10px;border-radius:9px;cursor:pointer}",
      ".kwp-back:hover{background:#f1f2f5;color:#18181a}",
      ".kwp-backChevron{font-size:18px;line-height:1}",
      ".kwp-entry{box-sizing:border-box;width:100%;height:36px;color:var(--dsw-alias-label-secondary);cursor:pointer;white-space:nowrap;background:0 0;border:none;border-radius:8px;align-items:center;gap:8px;padding:0 10px;font-size:13px;display:flex}",
      ".kwp-entry:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}",
      ".kwp-entry[data-active=true]{background:var(--dsw-specific-sidebar-nav-item-active);color:var(--dsw-alias-label-primary)}",
      ".kwp-entryIcon{flex:none;justify-content:center;align-items:center;width:24px;height:24px;display:inline-flex}",
      ".kwp-entryIcon svg{width:18px;height:18px;display:block}",
      ".kwp-entryLabel{text-overflow:ellipsis;overflow:hidden}",
      "body[data-kaiwu-plaza-open] [data-dsh-better-sidebar],body[data-kaiwu-plaza-open] [data-dsh-better-sidebar] *{pointer-events:none!important}",
      "[data-dsh-frame][data-sidebar-collapsed] .kwp-entry,[data-sidebar-collapsed] .kwp-entry{border-radius:50%;justify-content:center;width:36px;height:36px;margin:0 auto 12px;padding:0}",
      "[data-dsh-frame][data-sidebar-collapsed] .kwp-entryLabel,[data-sidebar-collapsed] .kwp-entryLabel{display:none}",
      // ---- 深色模式：跟随 DSH 主题（body[data-ds-dark-theme]）----
      "body[data-ds-dark-theme] .kwp-fixed{background:#141518;color:#f5f6f7}",
      "body[data-ds-dark-theme] .kwp-emptyHint{color:#757b84}",
      "body[data-ds-dark-theme] .kwp-card{background:#1c1d21;border-color:#26272c}",
      "body[data-ds-dark-theme] .kwp-cardBand{background:#26272c}",
      "body[data-ds-dark-theme] .kwp-name{color:#f5f6f7}",
      "body[data-ds-dark-theme] .kwp-role{color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-online{background:#1c1d21;color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-chatBtn{background:#1c1d21;color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-card:hover .kwp-chatBtn{color:#f5f6f7}",
      "body[data-ds-dark-theme] .kwp-desc{color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-wtag{color:#a6abb4;border-color:#3a3b41}",
      "body[data-ds-dark-theme] .kwp-stats{border-color:#2a2b2f}",
      "body[data-ds-dark-theme] .kwp-statCell{border-right-color:#26272c}",
      "body[data-ds-dark-theme] .kwp-statValue{color:#f5f6f7}",
      "body[data-ds-dark-theme] .kwp-statLabel{color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-back{color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-back:hover{background:#222329;color:#f5f6f7}",
      "body[data-ds-dark-theme] .kwp-hint{color:#757b84}",
      "body[data-ds-dark-theme] .kwp-loading{color:#a6abb4}",
      "body[data-ds-dark-theme] .kwp-error{color:#f87171}",
      // ---- 对话页：能力卡片 / 输入框小头像 / 悬停浮层（token 跟随 DSH 主题）----
      ".kwp-chatCard{box-sizing:border-box;width:100%;max-width:var(--dsh-composer-card-max-width,780px);margin:0 auto;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);border-radius:16px;padding:12px 14px;display:flex;flex-direction:column;gap:8px;color:var(--dsw-alias-label-primary);font-size:13px;line-height:20px}",
      ".kwp-chatHead{display:flex;align-items:center;gap:10px;min-width:0}",
      ".kwp-chatAvatar{width:32px;height:32px;border-radius:10px;color:#fff;display:flex;align-items:center;justify-content:center;font-size:15px;font-weight:700;flex:none}",
      ".kwp-avatarImg{width:100%;height:100%;object-fit:cover;display:block;border-radius:inherit;flex:none}",
      ".kwp-chatId{display:flex;flex-direction:column;gap:2px;min-width:0}",
      ".kwp-chatName{font-weight:600;color:var(--dsw-alias-label-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-chatRole{color:var(--dsw-alias-label-tertiary);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-chatDesc{color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}",
      ".kwp-chatTags{display:flex;flex-wrap:wrap;gap:6px}",
      ".kwp-chatTag{font-size:11px;line-height:18px;padding:0 8px;border-radius:999px;border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary)}",
      ".kwp-chatStats{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--dsw-alias-border-l2);border-radius:12px;overflow:hidden}",
      ".kwp-chatStat{padding:6px 10px;display:flex;flex-direction:column;gap:2px;border-right:1px solid var(--dsw-alias-border-l2)}",
      ".kwp-chatStat:last-child{border-right:0}",
      ".kwp-chatStatValue{font-size:16px;font-weight:700;line-height:20px;color:var(--dsw-alias-label-primary)}",
      ".kwp-chatStatLabel{font-size:11px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-workerChip{position:relative;display:inline-flex}",
      ".kwp-workerDockRow{box-sizing:border-box;width:100%;max-width:var(--dsh-composer-card-max-width,780px);margin:0 auto;display:flex;justify-content:flex-start;padding:0 12px}",
      ".kwp-workerBtn{width:30px;height:30px;border-radius:10px;border:1px solid var(--dsw-alias-border-l2);color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700;padding:0;box-shadow:0 2px 8px rgba(0,0,0,.18);background:var(--dsw-alias-button-primary-fill)}",
      ".kwp-workerPop{position:absolute;bottom:calc(100% + 10px);left:0;width:300px;z-index:80}",
      ".kwp-workerPop .kwp-chatCard{box-shadow:0 16px 40px rgba(0,0,0,.25)}",
      // ---- 管理端 ----
      ".kwp-topRight{margin-left:auto;display:flex;align-items:center;gap:8px}",
      ".kwp-topRight[data-anchored=true]{position:fixed;top:3px;z-index:2147483647;height:28px;margin:0}",
      ".kwp-ghostBtn{height:28px;border:0;background:transparent;color:var(--dsw-alias-label-secondary);border-radius:9px;padding:0 10px;font-size:13px;cursor:pointer;font-family:inherit;white-space:nowrap}",
      ".kwp-ghostBtn:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}",
      ".kwp-adminRoot{flex:1;min-height:0;display:flex;padding:0 28px 22px;gap:16px;overflow:hidden}",
      ".kwp-adminNav{width:236px;flex:none;display:flex;flex-direction:column;gap:6px;overflow:auto}",
      ".kwp-adminWorker{display:flex;align-items:center;gap:10px;padding:10px;border-radius:12px;border:1px solid transparent;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;text-align:left;font:inherit}",
      ".kwp-adminWorker:hover{background:var(--dsw-alias-interactive-bg-hover)}",
      ".kwp-adminWorker[data-active=true]{background:var(--dsw-specific-sidebar-nav-item-active);color:var(--dsw-alias-label-primary)}",
      ".kwp-adminWorkerAvatar{width:34px;height:34px;border-radius:10px;color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:15px;flex:none}",
      ".kwp-adminWorkerId{display:flex;flex-direction:column;gap:2px;min-width:0}",
      ".kwp-adminWorkerName{font-weight:600;color:inherit;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-adminWorkerRole{font-size:12px;color:var(--dsw-alias-label-tertiary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-adminPanel{flex:1;min-width:0;display:flex;flex-direction:column;overflow:hidden}",
      ".kwp-adminTabs{display:flex;gap:18px;border-bottom:1px solid var(--dsw-alias-border-l2);margin-bottom:12px;flex:none}",
      ".kwp-adminTab{padding:8px 2px;border:none;background:none;color:var(--dsw-alias-label-tertiary);cursor:pointer;font-size:13px;font-weight:500;border-bottom:2px solid transparent;font-family:inherit}",
      ".kwp-adminTab[data-active=true]{color:var(--dsw-alias-label-primary);border-bottom-color:var(--dsw-alias-label-primary);font-weight:600}",
      ".kwp-adminBody{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;gap:8px;padding-bottom:12px}",
      ".kwp-adminRow{display:flex;align-items:center;gap:10px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);border-radius:12px;padding:10px 12px}",
      ".kwp-adminRowMain{flex:1;min-width:0}",
      ".kwp-adminRowTitle{font-weight:600;color:var(--dsw-alias-label-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-adminRowDesc{font-size:12px;color:var(--dsw-alias-label-tertiary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".kwp-adminBtn{flex:none;border:1px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-secondary);border-radius:9px;padding:6px 12px;font-size:12px;cursor:pointer;font-family:inherit}",
      ".kwp-adminBtn:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}",
      ".kwp-adminBtnPrimary{background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground);border-color:transparent}",
      ".kwp-adminBtnPrimary:hover{background:var(--dsw-alias-button-primary-hover)}",
      ".kwp-adminEditor{display:flex;flex-direction:column;gap:8px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);border-radius:12px;padding:12px}",
      ".kwp-adminInput{box-sizing:border-box;width:100%;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);border-radius:8px;padding:8px 10px;font:inherit}",
      ".kwp-adminTextarea{box-sizing:border-box;width:100%;min-height:180px;resize:vertical;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);border-radius:8px;padding:8px 10px;font:inherit;font-family:var(--ds-font-family-code,Consolas,monospace);font-size:12px;line-height:18px}",
      ".kwp-adminActions{display:flex;gap:8px;justify-content:flex-end;margin-top:2px}",
      ".kwp-adminEmpty{color:var(--dsw-alias-label-tertiary);font-size:13px;padding:24px;text-align:center}",
      ".kwp-adminHint{font-size:12px;color:var(--dsw-alias-label-tertiary);line-height:18px;margin:0}",
      ".kwp-adminSkill{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);border-radius:12px;padding:10px 12px}",
      ".kwp-adminSkill summary{cursor:pointer;font-weight:600;color:var(--dsw-alias-label-primary);font-size:13px}",
      ".kwp-adminSkillDesc{font-size:12px;color:var(--dsw-alias-label-tertiary);margin-top:2px}",
      ".kwp-adminSkillBody{margin-top:8px;font-size:12px;color:var(--dsw-alias-label-secondary);white-space:pre-wrap;max-height:320px;overflow:auto;background:var(--dsw-alias-bg-layer-2);border-radius:8px;padding:8px 10px}",
      ".kwp-capabilityGroup{display:flex;flex-direction:column;gap:8px;padding:12px 0 18px;border-bottom:1px solid var(--dsw-alias-border-l2)}",
      ".kwp-capabilityGroup:last-child{border-bottom:0}",
      ".kwp-capabilityHead{display:flex;align-items:center;justify-content:space-between;gap:12px}",
      ".kwp-capabilityTitle{font-size:15px;font-weight:650;color:var(--dsw-alias-label-primary)}",
      ".kwp-capabilityMeta{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:5px}",
      ".kwp-capabilityDeleted{opacity:.58}",
      ".kwp-adminError{color:var(--dsw-alias-state-error-primary);font-size:12px;line-height:18px}",
      ".kwp-adminNavSection{font-size:11px;color:var(--dsw-alias-label-tertiary);padding:12px 10px 4px}",
      ".kwp-adminNavItem{display:flex;align-items:center;gap:8px;width:100%;border:0;background:transparent;color:var(--dsw-alias-label-secondary);border-radius:9px;padding:8px 10px;font:inherit;font-size:13px;text-align:left;cursor:pointer}",
      ".kwp-adminNavItem:hover{background:var(--dsw-alias-interactive-bg-hover)}",
      ".kwp-adminNavItem[data-active=true]{background:var(--dsw-specific-sidebar-nav-item-active);color:var(--dsw-alias-label-primary);font-weight:600}",
      ".kwp-adminProfile{display:flex;align-items:center;gap:18px;padding:4px 2px 16px;border-bottom:1px solid var(--dsw-alias-border-l2);margin-bottom:12px}",
      ".kwp-adminProfileAvatar{width:86px;height:96px;border-radius:20px;overflow:hidden;flex:none;display:flex;align-items:center;justify-content:center;color:#fff;font-size:28px;font-weight:700}",
      ".kwp-adminProfileMain{flex:1;min-width:0}",
      ".kwp-adminProfileTitle{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}",
      ".kwp-adminProfileTitle strong{font-size:22px;color:var(--dsw-alias-label-primary)}",
      ".kwp-adminProfileRole{font-size:13px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-adminMeta{display:flex;gap:14px;flex-wrap:wrap;margin-top:7px;color:var(--dsw-alias-label-tertiary);font-size:12px}",
      ".kwp-adminStatus{display:inline-flex;align-items:center;gap:5px;color:#16a34a}",
      ".kwp-adminStatus:before{content:'';width:7px;height:7px;border-radius:50%;background:#22c55e}",
      ".kwp-adminSummary{margin:8px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px;max-width:900px}",
      ".kwp-adminCounts{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}",
      ".kwp-adminCount{min-width:104px;background:var(--dsw-alias-bg-layer-2);border-radius:10px;padding:6px 12px;color:var(--dsw-alias-label-secondary);font-size:12px}",
      ".kwp-adminCount strong{font-size:15px;color:var(--dsw-alias-label-primary);margin-right:4px}",
      ".kwp-adminMetricGrid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:12px;margin-bottom:10px}",
      ".kwp-adminMetric{border:1px solid var(--dsw-alias-border-l2);border-radius:16px;padding:15px 18px;background:var(--dsw-alias-bg-layer-1)}",
      ".kwp-adminMetric strong{display:block;font-size:24px;color:var(--dsw-alias-label-primary);line-height:30px}",
      ".kwp-adminMetric span{font-size:12px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-adminSectionTitle{font-size:14px;font-weight:600;color:var(--dsw-alias-label-primary);margin:8px 0 2px}",
      ".kwp-adminTable{width:100%;border-collapse:separate;border-spacing:0;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;overflow:hidden;background:var(--dsw-alias-bg-layer-1);font-size:12px}",
      ".kwp-adminTable th,.kwp-adminTable td{text-align:left;padding:10px 12px;border-bottom:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary)}",
      ".kwp-adminTable th{font-weight:600;color:var(--dsw-alias-label-tertiary);background:var(--dsw-alias-bg-layer-2)}",
      ".kwp-adminTable tr:last-child td{border-bottom:0}",
      ".kwp-adminBadge{display:inline-flex;align-items:center;border-radius:999px;padding:2px 8px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary)}",
      ".kwp-adminBadge[data-running=true]{color:#15803d;background:#dcfce7}",
      ".kwp-adminSwitch{border:1px solid var(--dsw-alias-border-l2);border-radius:999px;padding:3px 9px;background:transparent;color:var(--dsw-alias-label-tertiary);font-size:11px;cursor:pointer}",
      ".kwp-adminSwitch[data-enabled=true]{background:#dcfce7;color:#15803d;border-color:#bbf7d0}",
      ".kwp-adminNotice{border:1px solid #fde68a;background:#fffbeb;color:#92400e;border-radius:10px;padding:9px 12px;font-size:12px;line-height:18px}",
      ".kwp-guide{border:1px solid var(--dsw-alias-stroke-subtle);border-radius:12px;background:var(--dsw-alias-bg-subtle);margin-bottom:12px;overflow:hidden}.kwp-guide summary{cursor:pointer;list-style:none;padding:10px 12px;font-size:13px;font-weight:650;color:var(--dsw-alias-label-primary)}.kwp-guide summary::-webkit-details-marker{display:none}.kwp-guide summary:after{content:'展开';float:right;color:var(--dsw-alias-label-secondary);font-size:11px;font-weight:400}.kwp-guide[open] summary:after{content:'收起'}.kwp-guideBody{border-top:1px solid var(--dsw-alias-stroke-subtle);padding:9px 14px 12px}.kwp-guideBody ol{margin:0;padding-left:20px;font-size:12px;line-height:1.85;color:var(--dsw-alias-label-secondary)}.kwp-guideBody p{margin:8px 0 0;font-size:12px;line-height:1.7;color:#92400e}",
      ".kwp-adminProfileForm{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}",
      ".kwp-adminProfileForm .kwp-adminTextarea{grid-column:1/-1;min-height:88px}",
      ".kwp-adminProfileForm .kwp-adminInputWide{grid-column:span 2}",
      ".kwp-adminProfileForm label{display:flex;flex-direction:column;gap:4px;font-size:11px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-adminProfileForm label>span{padding-left:2px}",
      ".kwp-profileBlock{border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1);padding:14px 16px;display:flex;flex-direction:column;gap:10px;margin-top:12px}",
      ".kwp-profileBlockTitle{font-size:14px;font-weight:650;color:var(--dsw-alias-label-primary)}",
      ".kwp-profileGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 18px}",
      ".kwp-profileField{display:flex;flex-direction:column;gap:3px;min-width:0}",
      ".kwp-profileField label{font-size:11px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-profileField span{font-size:13px;color:var(--dsw-alias-label-primary);line-height:1.45;word-break:break-word;white-space:pre-wrap}",
      ".kwp-profileChips{display:flex;flex-wrap:wrap;gap:6px}",
      ".kwp-profileChip{font-size:12px;padding:4px 10px;border-radius:999px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary)}",
      ".kwp-profileChipEmpty{font-size:12px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-adminBadgeNo{font-family:var(--ds-font-family-code,Consolas,monospace);font-size:12px;padding:2px 8px;border-radius:8px;border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary)}",
      ".kwp-capCards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:4px}",
      ".kwp-capCard{border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1);padding:12px 14px;display:flex;flex-direction:column;gap:6px;min-width:0}",
      ".kwp-capCard strong{font-size:22px;line-height:1;color:var(--dsw-alias-label-primary)}",
      ".kwp-capCard .kwp-capCardLabel{font-size:12px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-capCard .kwp-capCardBody{font-size:11px;line-height:1.45;color:var(--dsw-alias-label-secondary);word-break:break-word}",
      ".kwp-growthRail{display:flex;gap:16px;overflow-x:auto;padding:8px 2px 4px}",
      ".kwp-growthItem{position:relative;display:flex;flex-direction:column;align-items:center;gap:8px;min-width:140px}",
      ".kwp-growthItem:before{content:'';position:absolute;left:-12px;right:-12px;top:28px;height:1px;background:var(--dsw-alias-border-l2)}",
      ".kwp-growthDot{position:relative;z-index:1;width:8px;height:8px;border-radius:50%;background:var(--dsw-alias-label-primary)}",
      ".kwp-growthCard{width:136px;border-radius:14px;background:var(--dsw-alias-bg-layer-2);padding:10px 14px;display:flex;flex-direction:column;gap:4px}",
      ".kwp-growthKind{font-size:10px;color:var(--dsw-alias-label-tertiary)}",
      ".kwp-growthTitle{font-size:12px;color:var(--dsw-alias-label-secondary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
      ".kwp-growthDate{font-size:12px;font-weight:600;color:var(--dsw-alias-label-primary)}",
      ".kwp-metricClick{cursor:default}",
      ".kwp-metricPositive strong{color:#2cb360}",
      ".kwp-metricNegative strong{color:#d20b0b}",
      ".kwp-auditDetail{max-width:420px;white-space:normal!important;line-height:18px}",
      ".kwp-statusDot{display:inline-flex;align-items:center;gap:6px;color:#15803d}",
      ".kwp-statusDot:before{content:'';width:7px;height:7px;border-radius:50%;background:#22c55e}",
      "@media(max-width:900px){.kwp-adminNav{width:190px}.kwp-adminMetricGrid{grid-template-columns:repeat(2,1fr)}.kwp-adminProfileAvatar{width:64px;height:72px}.kwp-adminProfileForm{grid-template-columns:1fr}.kwp-profileGrid{grid-template-columns:1fr}.kwp-capCards{grid-template-columns:1fr}.kwp-adminProfileForm .kwp-adminInputWide{grid-column:1/-1}}",
      // ---- P0 交付前暂隐藏（代码保留，客户版恢复时删掉这几条即可）----
      ".kwp-card .kwp-stats{display:none}",
      ".kwp-chatStats{display:none}",
      // ---- 原生品牌替换用的 logo 图（黑色 → 深色主题 invert 变白）----
      ".kwp-kwlogo{user-select:none;pointer-events:none}",
      "body[data-ds-dark-theme] .kwp-kwlogo{filter:invert(1)}",
      // 客户版：隐藏新对话区「员工切换」座位按钮（conversation.hero.agentPreset，紧挨工作区 chip）
      "button[class*='cubgiG_seat']{display:none!important}"
    ].join("");
    var CSS_TAG = "kaiwu-praxis/plaza.module.css";
    if (typeof document !== "undefined" && document.querySelector('style[data-plugin-css="' + CSS_TAG + '"]') === null) {
      var styleEl = document.createElement("style");
      styleEl.dataset.plugin = "kaiwu-praxis";
      styleEl.dataset.pluginCss = CSS_TAG;
      styleEl.textContent = CSS;
      document.head.appendChild(styleEl);
    }

    // ---------------------------------------------------------------------
